#!/bin/bash

DISK=""                 # use lsblk and add the drive: sda, sdb, nvme0n1, etc 
BOOT_PART=""            # Leave Empty   (Unless you know what this should be)
SWAP_PART=""            # Leave Empty   (Unless you know what this should be)
ROOT_PART=""            # Leave Empty   (Unless you know what this should be)
FILESYSTEM=""           # ext4, BTRFS
EDITOR="nano"           # nano, vi, vim, nvim, emacs, etc
DESKTOP="KDE Plasma"    # KDE Plasma, Gnome, XFCE4, MATE, Cinnamon, etc 
HOSTNAME=""             # What your computer is known as on networks
ROOT_PASSWORD=""        # The Root account password (Leave empty to disable *hardmode*)
USER_NAME=""            # Your primary user account's name
USER_SUDO=true          # Should your user account have sudo privileges
USER_PASSWORD=""        # The password for your user account
LOCALE="en_US.UTF-8"    # The Locale / language for your computer
TIMEZONE="Eastern"      # The timezone of your computer

init_test() {
    ping -c 1 google.com || ping_fail
    timedatectl && install
}

ping_fail() {
    clear
    prompt="Unfortunately an internet connection could not be established."
    prompt+="\nThe Arch installation process uses the network to download system packages."
    prompt+="\nIf you're using WiFi, please try 'iwctl station wlan0 connect SSID'"
    prompt+="\nyou may need to change 'wlan0' to match your hardware."
    echo -e $prompt
}

fail() {
    flag=$1

    clear
    prompt="Installation Failed: "

    case $flag in
        1) prompt+="Disk Paritioning" ;;
        2) prompt+="Disk Formatting" ;;
        3) prompt+="Disk Mounting" ;;
        4) prompt+="Base System" ;;
        5) prompt+="Generating FSTab" ;;
        6) prompt+="Chroot Steps" ;;
        7) prompt+="Mounting Root";;
        8) prompt+="Mounting Boot";;
        9) prompt+="Enabling Swap";;
    esac
    echo -e $prompt
}

install() {
    disk_partition || fail 1
    disk_format || fail 2
    mount_disks || fail 3
    base_packages || fail 4
    generate_fstab || fail 5
    chroot_steps || fail 6
}

disk_partition() {
    clear
    cat <<EOF | fdisk $DISK
g
n
1

+1024MiB
t
1
1
n
2

+4096MiB
t
2
swap
n
3


w
EOF
}

disk_format() {
    clear
    if [[ $DEVICE == *"nvme"* ]]; then
        BOOT_PART="/dev/${DEVICE}p1"
        SWAP_PART="/dev/${DEVICE}p2"
        ROOT_PART="/dev/${DEVICE}p3"
    else
        BOOT_PART="/dev/${DEVICE}1"
        SWAP_PART="/dev/${DEVICE}2"
        ROOT_PART="/dev/${DEVICE}3"
    fi

    mkfs.fat -F 32 $BOOT_PART
    mkswap $SWAP_PART
    if [[ $FILESYSTEM == "btrfs" ]]; then
        mkfs.$FILESYSTEM -f $ROOT_PART
    else
        yes | mkfs.$FILESYSTEM $ROOT_PART
    fi
}

mount_disks() {
    clear
    mount -v $ROOT_PART /mnt || fail 7
    mkdir -pv /mnt/boot/efi
    mount -v $BOOT_PART /mnt/boot/efi || fail 8
    swapon -v $SWAP_PART || fail 9
}

base_packages() {
    clear
    pacstrap -K /mnt base base-devel linux linux-firmware linux-headers $EDITOR
}

generate_fstab() {
    clear
    genfstab -U /mnt >> /mnt/etc/fstab
}

chroot_steps() {
    export TIMEZONE
    export LOCALE
    export HOSTNAME
    export DESKTOP
    export ROOT_PASSWORD
    export USER_NAME
    export USER_SUDO
    export USER_PASSWORD
    clear

    cat <<EOF > /mnt/chroot_steps.sh
#!/bin/bash

fail() {
    flag=$1
    clear

    prompt="Installation Failed: "

    case $flag in
        1) prompt+="TimeZone";;
        2) prompt+="Locale";;
        3) prompt+="Hostname";;
        4) prompt+="Desktop";;
        5) prompt+="Root Password";;
        6) prompt+="Username";;
        7) prompt+="User Sudo";;
        8) prompt+="User Password";;
        9) prompt+="Grub";;
        10) prompt+="InitRamFS";;
    esac
}

main() {
    set_timezone || fail 1
    set_locale || fail 2
    set_hostname || fail 3
    set_desktop || fail 4
    set_rootpw || fail 5
    set_username || fail 6
    set_user_sudo || fail 7
    set_userpass || fail 8
    install_grub || fail 9
    generate_initramfs || fail 10
}

set_timezone() {
    clear
    ln -sf /usr/share/zoneinfo/US/${TIMEZONE} /etc/localtime && hwclock --systohc
}

set_locale() {
    echo "LANG=${LOCALE}" > /etc/locale.conf && locale-gen
}

set_hostname() {
    echo "${HOSTNAME}" > /etc/hostname
}

set_desktop() {
    choice=$DESKTOP
    case $choice in
        "KDE Plasma") packages="plasma plasma-meta"
                    DISPLAY_MANAGER="sddm";;
        "Gnome") packages="gnome gnome-extra gdm"
                    DISPLAY_MANAGER="";;
        "XFCE4") packages="xfce4 xfce4-goodies"
                    DISPLAY_MANAGER="lightdm";;
        "MATE") packages="mate mate-extra"
                    DISPLAY_MANAGER="lightdm";;
        "Cinnamon") packages="cinnamon"
                    DISPLAY_MANAGER="lightdm";;
    esac
    pacman -Sy --noconfirm $packages $DISPLAY_MANAGER && enable_dm
}

enable_dm() {
    systemctl enable $DISPLAY_MANAGER
}

set_rootpw() {
    echo "root:$ROOT_PASSWORD" | chpasswd
}

set_username() {
    useradd -m -G audio,video -s /bin/bash $USER_NAME
}

set_user_sudo() {
    echo "Not yet, hun"
}

install_grub() {
    grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
    grub-mkconfig -o /boot/grub/grub.cfg
}

main
EOF

    chmod a+x /mnt/chroot_steps.sh
    arch-chroot /mnt chroot_steps.sh
}

init_test
