#!/bin/bash

source ./install_backend

ENDSTYLE="\Zn"
BOLD="\Zb"
BOLD_END="\ZB"
REVERSE="\Zr"
UNDERLINE="\Zu"
RED="\Z1"
GREEN="\Z2"
YELLOW="\Z3"
BLUE="\Z4"
CYAN="\Z6"

TERMINAL_RED="\e[31m"
TERMINAL_END="\e[0m"

BACKTITLE="Rarch Installer"

# Default Values
DEVICE=""
SWAP=""
FILE_SYSTEM=""
TEXT_EDITOR=""
root_pass_set=false
AUR_WRAPPER="none"
DESKTOP="None (TTY Only)"
GRAPHICS_PROMPT=0
account_created=false
HOST_NAME=""
SELECTED_LOCALE="en_US.UTF-8"
DEFAULT_LOCALE=true
prompt_argument=1
ERROR=0
ROOT_INCORRECT=1
required=5

trap 'aborted' INT

aborted() {
    clear
    prompt="${TERMINAL_RED}Rarch Installer has been Aborted.${TERMINAL_END}"
    prompt+="\nIf this was due to a bug or issue, please report it to the the Github."
    prompt+="\n\nhttps://github.com/RileyMeta/Arch_Installer/issues/new"
    prompt+="\n"
    echo -e $prompt
    exit 0
}

init_test() {
    total_ram=$(free -m | awk '/^Mem:/{print $2}')
    dialog_test=$(ls /usr/bin/dialog)

    if [ "$total_ram" -le 2048 ]; then
        _ram_fail
    else
        ping -c 1 google.com || _ping_fail
    fi
    pacman -Sy --noconfirm dialog
    main
}

_menu_checks() {
    prompt=""
    case $prompt_argument in
        1) prompt+="${BOLD}Welcome to Riley's Arch Installer${ENDSTYLE}"
           prompt+="\nUse the steps below to configure your system the way you want.";;
        2) prompt+="${BOLD}Please review all your info below.${ENDSTYLE}"
           prompt+="\nIf there are any changes you would like to make, simply type the label name"
           prompt+="\nand you will be taken to that section so you can make changes.";;
        3) prompt+="${RED}${BOLD}The script cannot conitnue, please select your storage drive.${ENDSTYLE}";;
        4) prompt+="${RED}${BOLD}The script cannot conitnue, please select a Filesystem.${ENDSTYLE}";;
        5) prompt+="${RED}${BOLD}The script cannot conitnue, please select a Text Editor.${ENDSTYLE}";;
        6) prompt+="${RED}${BOLD}The script cannot conitnue, please set a root password.${ENDSTYLE}";;
        7) prompt+="${RED}${BOLD}The script cannot conitnue, please select a Desktop.${ENDSTYLE}";;
        8) prompt+="${RED}${BOLD}The script cannot conitnue, please set a Hostname.${ENDSTYLE}";;
        98) prompt+="${YELLOW}System Install Aborted at last minute. \n${BOLD}Nothing has been changed.${ENDSTYLE}";;
        99) prompt+="${GREEN}${BOLD}Installation Completed Successfully!${ENDSTYLE}"
            prompt+="\n${YELLOW}Restart to use your new system${ENDSTYLE}";;
    esac
        LOCALE_LABEL="Locale: ${GREEN}${SELECTED_LOCALE}${ENDSTYLE}"
    if [[ $DEFAULT_LOCALE = true ]]; then
        LOCALE_LABEL+=" *default"
    fi
    if [[ ${NEW_HOST_NAME} != "" ]]; then
        HOSTNAME_LABEL="Hostname: ${GREEN}${NEW_HOST_NAME}${ENDSTYLE}" 
    else
        HOSTNAME_LABEL="Hostname: ${RED}not set${ENDSTYLE}"
    fi
    if [[ $DEVICE != "" ]]; then
        DISKS_LABEL="Disk Selection: ${GREEN}${DEVICE}${ENDSTYLE}"
    else
        DISKS_LABEL="Disk Selection: ${RED}not set${ENDSTYLE}" 
    fi
    if [[ $FILE_SYSTEM != '' ]]; then
        FS_LABEL="File System: ${GREEN}${FILE_SYSTEM}${ENDSTYLE}" 
    else
        FS_LABEL="File System: ${RED}not set${ENDSTYLE}"
    fi
    if [[ $SWAP = true ]]; then
        SWAP_LABEL="Swap: ${CYAN}Enabled${ENDSTYLE}"
    else
        SWAP_LABEL="Swap: ${CYAN}Disabled${ENDSTYLE}"
    fi
    if [[ $TEXT_EDITOR != '' ]]; then
        if [[ $SYMLINK = true ]]; then
            TEXT_EDITOR_LABEL="Text Editor: ${GREEN}${TEXT_EDITOR}*${ENDSTYLE}"
        else
            TEXT_EDITOR_LABEL="Text Editor: ${GREEN}${TEXT_EDITOR}${ENDSTYLE}"
        fi
    elif [[ $TEXT_EDITOR = 'none' ]]; then
        TEXT_EDITOR_LABEL="Text Editor: ${GREEN}None${ENDSTYLE}"
    else
        TEXT_EDITOR_LABEL="Text Editor: ${RED}not set${ENDSTYLE}"
    fi
    if [[ $root_pass_set = true ]]; then
        ROOT_PASS_LABEL="Root Password: ${GREEN}set${ENDSTYLE}" 
    else
        ROOT_PASS_LABEL="Root Password: ${RED}not set${ENDSTYLE}"
    fi
    if [[ $AUR_WRAPPER != 'none' ]]; then
        AUR_LABEL="AUR Wrapper: ${GREEN}${AUR_WRAPPER}${ENDSTYLE}"
    else
        AUR_LABEL="AUR Wrapper: ${CYAN}None Chosen${ENDSTYLE}"
    fi
    DESKTOP_LABEL="Desktop: ${GREEN}${DESKTOP}${ENDSTYLE}"
    GPU_DRIVER_LABEL="Graphics Driver: ${GREEN}"
    case $GRAPHICS_PROMPT in
        0) GPU_DRIVER_LABEL+="None ${ENDSTYLE}*default";;
        1) GPU_DRIVER_LABEL+="Nvidia Proprietary";;
        2) GPU_DRIVER_LABEL+="Nvidia OpenKernel";;
        3) GPU_DRIVER_LABEL+="Nvidia OpenSource";;
        4) GPU_DRIVER_LABEL+="Nvidia OpenSource";;
        5) GPU_DRIVER_LABEL+="Intel";;
        6) GPU_DRIVER_LABEL+="AMD";;
        7) GPU_DRIVER_LABEL+="Mesa ${ENDSTYLE}*backend only";;
        8) GPU_DRIVER_LABEL+="No Drivers";;
    esac
    GPU_DRIVER_LABEL+="${ENDSTYLE}"
    if [[ $account_created = true ]]; then
        if [[ $SUDOER = true ]]; then
            USER_ACCOUNT_LABEL="User Account: ${GREEN}${NEW_USERNAME}${ENDSTYLE}*"
        else
            USER_ACCOUNT_LABEL="User Account: ${GREEN}${NEW_USERNAME}${ENDSTYLE}"
        fi
    else
        USER_ACCOUNT_LABEL="User Account: ${CYAN}No User Account${ENDSTYLE}"
    fi
    if [[ $ERROR != 1 ]]; then
        MAIN_TITLE="Main Menu"
    else
        MAIN_TITLE="An Error has occurred"
    fi
    if [[ $required != 0 ]]; then
        INSTALL_LABEL="${REVERSE}${RED}Install${ENDSTYLE}"
    else
        INSTALL_LABEL="${REVERSE}${GREEN}Install${ENDSTYLE}"
    fi
}

main() {
    _menu_checks
    while true; do
    mainMenuOptions=(
    1 "${LOCALE_LABEL}"
    2 "${HOSTNAME_LABEL}"
    3 "${DISKS_LABEL}"
    4 "${FS_LABEL}"
    5 "${SWAP_LABEL}"
    6 "${ROOT_PASS_LABEL}"
    7 "${USER_ACCOUNT_LABEL}"
    8 "${TEXT_EDITOR_LABEL}"
    9 "${DESKTOP_LABEL}"
    10 "${GPU_DRIVER_LABEL}"
    11 "${AUR_LABEL}"
    12 "${INSTALL_LABEL}"
)
result=$(dialog --clear --title "${MAIN_TITLE}" \
    --backtitle "$BACKTITLE" \
    --colors \
    --default-item "$default_item" \
    --cancel-label "Exit" \
    --stdout \
    --menu "${prompt}" 0 0 10 "${mainMenuOptions[@]}")

case $? in
    0)  case $result in
            1) locale_selection
                break ;;
            2) hostname
                break ;;
            3) disk_selection
                break ;;
            4) filesystem
                break ;;
            5) swap_config
                break ;;
            6) root_password
                break ;;
            7) account_creation
                break ;;
            8) texteditor
                break ;;
            9) choose_desktop
                break ;;
            10) graphics_drivers
                break ;;
            11) aur_wrapper
                break ;;
            12) _install_check
                break ;;
        esac
        ;;
    1) clear 
        exit 1 ;;
esac
    done
}

locale_selection() {
    options=("af_ZA" "ar_SA" "be_BY" "bg_BG" "bs_BA" "ca_ES" "cs_CZ" "da_DK" "de_DE" "el_GR" "en_GU" "en_US" "es_ES" "et_EE" "eu_ES" "fa_IR" "fi_FI" "fil_P" "fr_BE" "fr_CA" "fr_CH" "fr_FR" "ga_IE" "gl_ES" "he_IL" "hi_IN" "hr_HR" "hu_HU" "id_ID" "is_IS" "it_IT" "ja_JP" "ka_GE" "km_KH" "kn_IN" "ko_KR" "lo_LA" "lt_LT" "mi_NZ" "mi_NZ" "mi_NZ" "mi_NZ" "ml_IN" "mn_MN" "ms_MY" "nl_NL" "nn_NO" "no_NO" "no_NO" "pl_PL" "pt_BR" "pt_PT" "pt_TL" "ro_RO" "ru_RU" "sk_SK" "sl_SI" "so_SO" "sq_AL" "sr_CS" "sv_SE" "ta_IN" "th_TH" "tr_TR" "uk_UA" "vi_VN" "zh_CN" "zh_TW")

    menu_options=()
    i=1
    for option in "${options[@]}"; do
        menu_options+=("$i" "$option")
        ((i++))
    done

    exec 3>&1
    if [ $DEFAULT_LOCALE = true ]; then
        locale_message="Default: ${CYAN}${SELECTED_LOCALE}${ENDSTYLE}"
    else
        locale_message="Current Selection: ${CYAN}${SELECTED_LOCALE}${ENDSTYLE}"
    fi
    locale_message+="\nPlease select your Locale"
    locale_message+="\n\nor press 'Skip' to confirm the default"
    if [ $DEFAULT_LOCALE = true ]; then
        LOCALE_CANCEL_LABEL="SKIP"
    else
        LOCALE_CANCEL_LABEL="BACK"
    fi
    selection=$(dialog --clear \
                       --title "Locale Selection" \
                       --colors \
                       --ok-label "SELECT" \
                       --cancel-label "${LOCALE_CANCEL_LABEL}" \
                       --menu "${locale_message}" 15 40 10 \
                       "${menu_options[@]}" \
                       2>&1 1>&3)
    exec 3>&-

    if [ -n "$selection" ]; then
        chosen_option="${options[$((selection - 1))]}"
        SELECTED_LOCALE="${chosen_option}.UTF-8"
        DEFAULT_LOCALE=false
        main
    else
        if [ $DEFAULT_LOCALE = true ];then 
            SELECTED_LOCALE="en_US.UTF-8"
            DEFAULT_LOCALE=false
            default_item=2
        else
            SELECTED_LOCALE="${SELECTED_LOCALE}"
        fi
        main
    fi
}

_install_check() {
    if [[ $NEW_HOST_NAME = "" ]]; then
        prompt_argument=8
        ERROR=1
        main
    elif [[ $DEVICE = "" ]]; then
        prompt_argument=3
        ERROR=1
        main
    elif [[ $FILE_SYSTEM = "" ]]; then
        prompt_argument=4
        ERROR=1
        main
    elif [[ $ROOT_PW_CONFIRM = "" ]]; then
        prompt_argument=6
        ERROR=1
        main
    elif [[ $TEXT_EDITOR = "" ]]; then
        prompt_argument=5
        ERROR=1
        main
    else
        install_confirmation
    fi
}

disk_selection() {
    DISK_SELECT_PROMPT="Below are your Available Storage Devices:\n"
    output=$(lsblk -Ald -o NAME,SIZE,RM)

    while IFS= read -r line; do
        name=$(echo "$line" | awk '{print $1}')
        size=$(echo "$line" | awk '{print $2}')
        rm=$(echo "$line" | awk '{print $3}')

        if [[ "$name" != *"SWAP"* && "$name" != *"zram0"* && "$name" != *"NAME"* ]]; then
            if [[ "$rm" -eq 1 ]]; then
                DISK_SELECT_PROMPT+="\n$name ${BLUE}${size}${ENDSTYLE} ${REVERSE}${YELLOW}[Removable]${ENDSTYLE}"
            else
                DISK_SELECT_PROMPT+="\n$name ${BLUE}${size}${ENDSTYLE}"
            fi
        fi
    done <<< "$output"
    DISK_SELECT_PROMPT+="\n\nPlease Select the Disk you would like to install Linux to"
    mapfile -t options < <(lsblk -Ald -o NAME | tail -n +2)

    menu_options=""
    i=1
    for option in "${options[@]}"; do
        if [[ "$option" != "zram0" && "$option" != "NAME" && "$option" != *SWAP* ]]; then
            menu_options+="$i $option "
            ((i++))
        fi
    done

    exec 3>&1
    selection=$(dialog --clear \
                       --backtitle "${BACKTITLE}" \
                       --colors \
                       --title "Disk Selection" \
                       --cancel-label "BACK" \
                       --ok-label "SELECT" \
                       --menu "${DISK_SELECT_PROMPT}" 0 0 0 \
                       $menu_options \
                       2>&1 1>&3)
    exec 3>&-

    if [ -n "$selection" ]; then
        chosen_option=$(echo "$menu_options" | awk -v sel="$selection" '{for(i=1; i<=NF; i+=2) if($i == sel) print $(i+1)}')
        DEVICE="${chosen_option}"
        STEP_CONFIRM=1
        CONFIRM_MESSAGE=1
        (($required--))
        _drive_confirmation
    else
        main
    fi
}

_drive_confirmation() {
    if dialog --clear \
    --backtitle "${BACKTITLE}" \
    --colors \
    --title "Disk Confirmation" \
    --yesno "Are you sure you would like to use ${CYAN}${DEVICE}${ENDSTYLE}?" 0 0 ; then
        _drive_partitioning
    else
        DEVICE=""
        disk_selection
    fi
}

_drive_partitioning() {
    partition_size=$(dialog --clear \
    --backtitle "${BACKTITLE}" \
    --colors \
    --title "Disk Partitioning" \
    --inputbox "A normal linux install will have 2 or 3 partitions \
    \n[Boot] Roughly 1GB\n[Swap] If you are planning on using Suspend, please set this to the same as your ram\n[Root] The home of your drive \
    \n[Home] *Optional* Not recommended for new users. Allows the user to save their home folder to a second drive or dedicated partition." 8 40 \
    --output-fd 1)

    if [ $? -eq 0 ]; then
        default_item=4
        main
    else
        main
    fi
}

hostname() {
    local NEW_HOST_NAME
    NEW_HOST_NAME=$(dialog --clear \
    --backtitle "${BACKTITLE}" \
    --colors \
    --title "Hostname" \
    --inputbox "Please set the Hostname for your computer:" 8 40 \
    --output-fd 1)

    if [ $? -eq 0 ]; then
        prompt_argument=1
        ERROR=0
        default_item=3
        (($required--))
        main
    else
        main
    fi
}

filesystem() {
    while true; do
    filesystemOptions=(
    1 "EXT4"
    2 "BTRFS"
)
result=$(dialog --clear --title "Filesystem Selection" \
    --backtitle "$BACKTITLE" \
    --colors \
    --cancel-label "Exit" \
    --stdout \
    --menu "\nPlease select your preferred file system" 0 0 3 "${filesystemOptions[@]}")

case $? in
    0)  case $result in
            1) FILE_SYSTEM="ext4"
                default_item=5
                (($required--))
                main
                break ;;
            2) FILE_SYSTEM="btrfs"
                default_item=5
                (($required--))
                main
                break ;;
        esac
        ;;
    1) main;;
esac
    done
}

swap_config() {
    if dialog --clear \
    --backtitle "${BACKTITLE}" \
    --colors \
    --title "Swap Partition" \
    --yesno "\nWould you like to use a ${CYAN}2GiB${ENDSTYLE} swap partition?" 0 0 ; then
        SWAP=true
        default_item=6
        (($required--))
        main
    else
        SWAP=false
        default_item=6
        (($required--))
        main
    fi
}

_root_pass_error() {        
    case ${ROOT_INCORRECT} in
        1) ROOT_PW_TITLE="Root Password"
            ROOT_PW_MSG="Please input your root Password";;
        2) ROOT_PW_TITLE="Please Try Again"
            ROOT_PW_MSG="The passwords you entered did not match. \nPlease try again.";;
        3) ROOT_PW_TITLE="Please Try Again"
            ROOT_PW_MSG="The Root Password cannot be blank. \nPlease try again.";;
    esac
}

root_password() {
    _root_pass_error
    ROOT_PW=$(dialog --clear \
    --backtitle "${BACKTITLE}" \
    --title "${ROOT_PW_TITLE}" \
    --insecure \
    --passwordbox "${ROOT_PW_MSG}" 0 0 \
    --output-fd 1)

    if [$? -eq 1 ]; then
        main
    else
        if [[ $ROOT_PW != "" ]]; then 
            _confirm_root_pw
        else
            ROOT_INCORRECT=3
            root_password
        fi
    fi
}

_confirm_root_pw() {
    ROOT_PW_CONFIRM=$(dialog --clear \
    --backtitle "${BACKTITLE}" \
    --title "Root Password" \
    --insecure \
    --passwordbox "Please confirm your root Password" 0 0 \
    --output-fd 1)

    if [$? -eq 1 ]; then
        main
    else
        if [[ $ROOT_PW_CONFIRM = $ROOT_PW ]]; then
            root_pass_set=true
            default_item=7
            (($required--))
            main
        else
            ROOT_INCORRECT=2
            root_password
        fi
    fi
}

account_creation() {
    if [[ $USERNAME_INCORRECT = true ]]; then
        USERNAME_PROMPT="A username cannot be blank. \nPlease try again."
    else
        USERNAME_PROMPT="Please type your username:"
    fi
    USERNAME=$(dialog --clear \
    --backtitle "${BACKTITLE}" \
    --title "User Account Creation" \
    --insecure \
    --inputbox "${USERNAME_PROMPT}" 0 0 \
    --output-fd 1)

    if [$? -eq 1 ]; then
        main
    else
        if [[ $USERNAME != "" ]]; then 
            USER_INCORRECT=1 # Default / Normal response
            NEW_USERNAME="${USERNAME,,}"
            default_item=8
            user_password_check
        else
            USERNAME_INCORRECT=true
            default_item=8
            account_creation
        fi
    fi
}

user_password_check() {
    if dialog --clear \
    --backtitle "${BACKTITLE}" \
    --colors \
    --title "User Account Password" \
    --yesno "Would you like ${BLUE}${NEW_USERNAME}${ENDSTYLE} to have a password?" 0 0; 
    then
        user_password
        user_pass=true
    else
        user_pass=false
        account_created=true
        main
    fi
}

user_sudoers_check() {
    if dialog --clear \
    --backtitle "${BACKTITLE}" \
    --colors \
    --title "Sudoers" \
    --yesno "Would you like ${BLUE}${NEW_USERNAME}${ENDSTYLE} to be a sudoer?" 0 0; 
    then
        SUDOER=true
        main
    else
        SUDOER=false
        main
    fi
}

_user_pass_error() {        
    case ${USER_INCORRECT} in
        "1") USER_PW_MSG="Please input your user Password";;
        "2") USER_PW_MSG="The passwords you entered did not match. \nPlease try again.";;
        "3") USER_PW_MSG="The User Password cannot be blank. \nPlease try again.";;
    esac
}

user_password() {
    _user_pass_error
    USER_PW=$(dialog --clear \
    --backtitle "${BACKTITLE}" \
    --title "User Password" \
    --insecure \
    --passwordbox "${USER_PW_MSG}" 0 0 \
    --output-fd 1)

    if [$? -eq 1 ]; then
        main
    else
        if [[ $USER_PW != "" ]]; then 
            _confirm_user_pw
        else
            USER_INCORRECT=3
            user_password
        fi
    fi
}

_confirm_user_pw() {
    USER_PW_CONFIRM=$(dialog --clear \
    --backtitle "${BACKTITLE}" \
    --title "User Password" \
    --insecure \
    --passwordbox "Please confirm your user Password" 0 0 \
    --output-fd 1)

    if [$? -eq 1 ]; then
        main
    else
        if [[ $USER_PW_CONFIRM = $USER_PW ]]; then
            user_pass_set=true
            account_created=true
            user_sudoers_check
        else
            USER_INCORRECT=2
            user_password
        fi
    fi
}

texteditor() {
    while true; do
    texteditorOptions=(
    1 "Vi" on \
    2 "Vim" off \
    3 "NeoVim" off \
    4 "Nano" off \
    5 "Emacs" off \
    6 "None" off
)
result=$(dialog --clear --title "Text Editor Selection" \
    --backtitle "$BACKTITLE" \
    --colors \
    --cancel-label "BACK" \
    --stdout \
    --checklist "\nPlease select your preferred console text editor" 0 0 6 "${texteditorOptions[@]}")

case $? in
    0)  case $result in
            1) TEXT_EDITOR="vi"
                default_item=9
                main
                break ;;
            2) TEXT_EDITOR="vim"
                default_item=9
                main
                break ;;
            3) TEXT_EDITOR="neovim"
                default_item=9
                text_editor_symlink
                break ;;
            4) TEXT_EDITOR="nano"
                default_item=9
                text_editor_symlink
                break ;;
            5) TEXT_EDITOR="emacs"
                default_item=9
                text_editor_symlink
                break ;;
            6) TEXT_EDITOR="none"
                default_item=9
                main
                break ;;
        esac
        (($required--))
        ;;
    1) main;;
esac
    done
}

text_editor_symlink() {
    if dialog --clear \
    --backtitle "${BACKTITLE}" \
    --colors \
    --title "User Account Password" \
    --yesno "Would you like to symlink ${BLUE}${TEXT_EDITOR}${ENDSTYLE} to /usr/bin/vi? \
    \n\nThis would allow you to work with apps that require vi (like Visudo)." 0 0;
    then
        SYMLINK=true
        main
    else
        main
    fi
}

choose_desktop() {
    while true; do
    desktopOptions=(
    1 "Gnome"
    2 "KDE Plasma"
    3 "XFCE"
    4 "None (TTY Only)"
)
result=$(dialog --clear --title "Desktop Environment" \
    --backtitle "$BACKTITLE" \
    --colors \
    --cancel-label "BACK" \
    --stdout \
    --menu "\nPlease select your preferred Desktop Environment" 0 0 3 "${desktopOptions[@]}")

case $? in
    0)  case $result in
            1) DESKTOP="Gnome"
                display_manager
                break ;;
            2) DESKTOP="Kde Plasma"
                display_manager
                break ;;
            3) DESKTOP="XFCE"
                display_manager
                break ;;
            4) DESKTOP="None (TTY Only)"
                display_manager
                break ;;
        esac
        ;;
    1) main;;
esac
    done
}

display_manager() {
    if [[ $DESKTOP = 'Gnome' ]]; then
        GDM_PROMPT="GDM (*Recommended for Gnome)"
    else
        GDM_PROMPT="GDM"
    fi

    while true; do
    displaymanagerOptions=(
    1 "${GDM_PROMPT}"
    2 "SDDM"
    3 "LightDM"
    4 "SX (StartX alternative)"
)
result=$(dialog --clear --title "Display Manager Selection" \
    --backtitle "$BACKTITLE" \
    --colors \
    --cancel-label "Exit" \
    --stdout \
    --menu "\nPlease select your preferred Display Manager" 0 0 3 "${displaymanagerOptions[@]}")

case $? in
    0)  case $result in
            1) DISPLAY_MANAGER="gdm"
                default_item=10
                main
                break ;;
            2) DISPLAY_MANAGER="sddm"
                default_item=10
                main
                break ;;
            3) DISPLAY_MANAGER="lightdm"
                default_item=10
                main
                break ;;
            4) DISPLAY_MANAGER="sx"
                default_item=10
                main
                break ;;
        esac
        ;;
    1) main;;
esac
    done
}

graphics_drivers() {
    while true; do
    graphicsdriverOptions=(
    1 "Nvidia (Proprietary)"
    2 "Nvidia (OpenKernel)"
    3 "Nvidia (vulkan-nouveau)"
    4 "Nvidia (xf86-video-nouveau)"
    5 "Intel (xf86-video-intel)"
    6 "AMD (xf86-video-amdgpu)"
    7 "Mesa (openGL drivers)"
    8 "None"
)
result=$(dialog --clear --title "Graphics Driver Selection" \
    --backtitle "$BACKTITLE" \
    --colors \
    --cancel-label "Exit" \
    --extra-button \
    --extra-label "More Info" \
    --stdout \
    --menu "\nPlease select your preferred graphics driver
    \n\nor check 'More Info' to see what all will be installed." 0 0 6 "${graphicsdriverOptions[@]}")

case $? in
    0)  case $result in
            1) GRAPHICS_DRIVER="nvidia-dkms nvidia-utils"
                GRAPHICS_PROMPT=1
                default_item=11
                main
                break ;;
            2) GRAPHICS_DRIVER="nvidia-open-dkms"
                GRAPHICS_PROMPT=2
                default_item=11
                main
                break ;;
            3) GRAPHICS_DRIVER="vulkan-nouveau mesa"
                GRAPHICS_PROMPT=3
                default_item=11
                main
                break ;;
            4) GRAPHICS_DRIVER="xf86-video-nouveau mesa"
                GRAPHICS_PROMPT=4
                default_item=11
                main
                break ;;
            5) GRAPHICS_DRIVER="xf86-video-intel mesa"
                GRAPHICS_PROMPT=5
                default_item=11
                main
                break ;;
            6) GRAPHICS_DRIVER="xf86-video-amdgpu mesa"
                GRAPHICS_PROMPT=6
                default_item=11
                main
                break ;;
            7) GRAPHICS_DRIVER="mesa"
                GRAPHICS_PROMPT=7
                default_item=11
                main
                break ;;
            8) GRAPHICS_DRIVER=""
                GRAPHICS_PROMPT=8
                default_item=11
                main
                break ;;
        esac
        ;;
    1) main
        break;;
    3) gpu_explain
        break;;
esac
    done
}

gpu_explain() {
    GPU_MESSAGE="\nBelow is a table explaining what drivers work for what GPUs:"
    GPU_MESSAGE+="\n\n${BOLD}==Type=====Driver===============GPU=================Backend============${BOLD_END}"
    GPU_MESSAGE+="\n| nvidia   ${GREEN}Proprietary${ENDSTYLE}          (10 series +)       ${CYAN}nvidia-utils${ENDSTYLE}      |"
    GPU_MESSAGE+="\n| nvidia   ${GREEN}OpenKernel${ENDSTYLE}           (16 series +)       ${CYAN}nvidia-utils${ENDSTYLE}      |"
    GPU_MESSAGE+="\n| nvidia   ${GREEN}vulkan-nouveau${ENDSTYLE}       (16 series +)       ${CYAN}mesa${ENDSTYLE}              |"
    GPU_MESSAGE+="\n| nvidia   ${GREEN}xf86-video-nouveau${ENDSTYLE}   (All*       )       ${CYAN}mesa${ENDSTYLE}              |"
    GPU_MESSAGE+="\n| intel    ${GREEN}xf86-video-intel${ENDSTYLE}     (Intel iGPU )       ${CYAN}mesa${ENDSTYLE}              |"
    GPU_MESSAGE+="\n| amd      ${GREEN}xf86-video-amdgpu${ENDSTYLE}    (AMD GPUs   )       ${CYAN}mesa${ENDSTYLE}              |"
    GPU_MESSAGE+="\n| mesa     *misc*               *ALL*               *is the backend*                                       |"
    GPU_MESSAGE+="\n${BOLD}=======================================================================${BOLD_END}"
    dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "GPU Driver Table" \
    --colors \
    --cr-wrap \
    --msgbox "$GPU_MESSAGE" 0 0
    if [[ $? = 0 ]]; then
        graphics_drivers
    fi
}

aur_wrapper() {
    while true; do
    aurwrapperOptions=(
    1 "Yay (Written in Go)"
    2 "Paru (Written in Rust)"
    3 "None"
)
result=$(dialog --clear --title "Aur Wrapper" \
    --backtitle "$BACKTITLE" \
    --colors \
    --cancel-label "BACK" \
    --stdout \
    --menu "\nAn AUR Wrapper (or Helper) is a tool that automates installing dependencies and packages from the Arch User Repository." 0 0 3 "${aurwrapperOptions[@]}")

case $? in
    0)  case $result in
            1) AUR_WRAPPER="yay"
                default_item=12
                main
                break ;;
            2) AUR_WRAPPER="paru"
                default_item=12
                main
                break ;;
            3) AUR_WRAPPER="none"
                default_item=12
                main
                break ;;
        esac
        ;;
    1) main;;
esac
    done
}

install_confirmation() {
    if dialog --clear \
    --backtitle "${BACKTITLE}" \
    --colors \
    --title "Final Install Confirmation" \
    --yes-label "YES, I AM SURE" \
    --no-label "NO, TAKE ME BACK" \
    --yesno "\nAre you sure you would like to continue with the Install?
    \n\n${RED}${UNDERLINE}This will completely erase all data on ${BOLD}$DEVICE${ENDSTYLE}" 0 0 ; then
        SYSTEM_INSTALL
    else
        prompt_argument=98
        main
    fi
}

SYSTEM_INSTALL() {
    full_install
    if [[ $account_created = true ]]; then
        _create_user
    fi
    case $AUR_WRAPPER in
        'yay') chroot_steps=1 && _install_yay;;
        'paru') chroot_steps=2 && _install_paru;;
        'none') : ;;
    esac
    if [[ $SYMLINK = true ]]; then
        _run_symlink
    fi
    clean_up
    SUCCESSFUL_FINISH
}

_run_pacman_config() {
    case $pacman_step in
        1) prompt="\nEnabling Parallel Downloads";;
        2) prompt="\nEnabling Colorful Output";;
        3) prompt="\nEnabling Verbose Package lists";;
    esac
    dialog --title "Configuring Pacman..." --backtitle "${BACKTITLE}" \
    --colors \
    --infobox "$prompt" 8 50
    case $pacman_step in
        1) sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 10/g' /etc/pacman.conf ;;
        2) sed -i 's/#Color/Color/g' /etc/pacman.conf ;;
        3) sed -i 's/#VerbosePkgLists/VerbosePkgLists/g' /etc/pacman.conf ;;
    esac
    sleep 1
}

_set_hostname() {
    dialog --title "Assigning Hostname..." --backtitle "${BACKTITLE}" \
    --colors \
    --infobox "echo $NEW_HOST_NAME > /etc/hostname" 8 50
    echo $NEW_HOST_NAME > /mnt/etc/hostname
    sleep 1
}

_set_locale() {
    dialog --title "Assigning Locale..." --backtitle "${BACKTITLE}" \
    --colors \
    --infobox "echo $SELECTED_LOCALE > /etc/locale.conf" 8 50
    echo $SELECTED_LOCALE > /mnt/etc/locale.conf
    sleep 1
}

SUCCESSFUL_FINISH() {
    if dialog --clear \
    --backtitle "${BACKTITLE}" \
    --colors \
    --title "Installation Successful!" \
    --yesno "\nWould you like to chroot into the new system?" 0 0;
    then
        echo "arch-chroot /mnt"
    else
        prompt_argument=99
        main
    fi
}

init_test
