#!/bin/bash

full_install() {
    _partition_drives
    _format_partitions
    _mount_drives
    _run_pacstrap
    _run_genfstab
    _set_rootpw
    _install_grub

    if [[ $account_created == true ]]; then
        _create_user
    fi
    _install_packages
    case $AUR_WRAPPER in
        'yay') _install_yay;;
        'paru') _install_paru;;
        'none') : ;;
    esac
    if [[ $SYMLINK = true ]]; then
        _run_symlink
    fi
    _run_systemd
    _set_hostname
    _set_locale
}

_partition_drives() {
    BOOT_SIZE=512
    SWAP_SIZE=4096
    format_boot="+${BOOT_SIZE}MiB"
    format_swap="+${SWAP_SIZE}MiB"

    if [[ $SWAP == true ]]; then
    cat <<EOF | fdisk $DEVICE
g
n
1

$format_boot
y
t
1
n
2

$format_swap
t
2
swap
n
3


w
EOF

    else
    cat <<EOF | fdisk $DEVICE
g
n
1

$format_boot
y
t
1
n
2


w
EOF
    fi
}

_format_partitions() {
    if [[ $DEVICE == *"nvme"* ]]; then
        DEVICE="${DEVICE}p"
    fi

    BOOT_DEVICE="${DEVICE}1"
    
    mkfs.fat -F 32 $BOOT_DEVICE
    mkdir -pv /mnt


    if [[ $SWAP == true ]]; then
        SWAP_DEVICE="${DEVICE}2"
        ROOT_DEVICE="${DEVICE}3"
        
        mkswap $SWAP_DEVICE
        swapon $SWAP_DEVICE
        
        if [[ $FILE_SYSTEM == 'btrfs' ]]; then
            mkfs.btrfs -f $ROOT_DEVICE
        else
            yes | mkfs.ext4 $ROOT_DEVICE
        fi
    else
        ROOT_DEVICE="${DEVICE}2"

        if [[ $FILE_SYSTEM == 'btrfs' ]]; then
          mkfs.btrfs -f $ROOT_DEVICE
        else
          yes | mkfs.ext4 $ROOT_DEVICE
        fi
    fi
}

_mount_drives() {
    if [[ $SWAP == true ]]; then
        mount /dev/vda3 /mnt
    else
        mount /dev/vda2 /mnt
    fi
    mkdir -pv /mnt/boot/efi
    mount /dev/vda1 /mnt/boot/efi
}

_run_pacstrap() {
    packages="base base-devel linux linux-firmware linux-headers sof-firmware grub efibootmgr git curl wget ${TEXT_EDITOR}"
    pacstrap -K /mnt $packages
}

_run_genfstab() {
    echo "Generating FSTab"
    genfstab -U /mnt >> /mnt/etc/fstab
}

_set_rootpw() {
    echo "Setting Root Password"
    arch-chroot /mnt echo "root:$ROOT_PW" | chpasswd
}

_install_grub() {
    mkdir -v /mnt/chroot
    cat <<EOF > /mnt/chroot/grub_install
#!/bin/bash

main() {
    mount /boot/efi
    grub-install --efi-directory=/boot/efi --target=x86_64-efi --bootloader-id=GRUB --removable
    grub-mkconfig -o /boot/grub/grub.cfg
}
main
EOF

    chmod a+x /mnt/chroot/grub_install
    arch-chroot /mnt /chroot/grub_install
}

_install_packages() {
    packages="sudo git curl wget efibootmgr efivar grub dosfstools "
    packages+="xdg-user-dirs xdg-desktop-portal xdg-utils extra/networkmanager "
    case $GRAPHICS_DRIVER in
        'Nvidia Proprietary') packages+="nvidia-dkms egl-wayland lib32-nvidia-utils lib32-opencl-nvidia nvidia-settings opencl-nvidia nvidia-utils ";;
        'Nvidia Open') packages+="nvidia-open-dkms egl-wayland lib32-nvidia-utils lib32-opencl-nvidia nvidia-settings opencl-nvidia nvidia-utils ";;
        'vulkan-nouveau') packages+="vulkan-nouveau mesa ";;
        'xf86-nouveau') packages+="xf86-video-nouveau mesa ";;
        'Intel') packages+="xf86-video-intel mesa ";;
        'AMD GPU') packages+="xf86-video-amdgpu mesa ";;
        'mesa') packages+="mesa ";;
    esac
    case $DESKTOP in
        'Gnome') packages+="gnome gnome-extra xdg-desktop-portal-gtk xdg-desktop-portal-gnome gnome-terminal ${DISPLAY_MANAGER} " ;;
        'Kde Plasma') packages+="plasma plasma-meta xdg-desktop-portal-kde kde-applications kde-utilities ${DISPLAY_MANAGER} " ;;
        'XFCE') packages+="xfce4 xfce4-goodies extra/xfce4-terminal ${DISPLAY_MANAGER} " ;;
    esac 
    if [[ "$AUR_WRAPPER" = "yay" ]]; then
        packages+="go "
    fi
    case $FILE_SYSTEM in
        "ext4") packages+="e2fsprogs " ;;
        "btrfs") packages+="btrfs-progs " ;;
    esac

    arch-chroot /mnt pacman -Sy --noconfirm $packages
}

_create_user() {
    echo "Creating User"
    arch-chroot /mnt useradd -m -G wheel,video,audio $USER_NAME -s /bin/bash
    echo "Applying User Password"
    arch-chroot /mnt echo '$USER_NAME:$user_pass' | chpasswd
    if [[ $SUDOER = true ]]; then
        echo "Adding User to Sudoers"
        arch-chroot /mnt sed -i "/^root.*ALL=(ALL:ALL) ALL/a\\${USER_NAME} ALL=(ALL:ALL) ALL" /etc/sudoers
    fi
}

_run_systemd() {
    systemd-nspawn -D /mnt -- systemctl enable $DISPLAY_MANAGER
    systemd-nspawn -D /mnt -- systemctl enable NetworkManager
}

_set_hostname() {
    echo -e "Setting Hostname\n>> echo '${NEW_HOST_NAME}' > /etc/hostname"
    echo "${NEW_HOST_NAME}" > /mnt/etc/hostname 
}

_set_locale() {
    echo -e "Setting Locale\n>> echo '${SELECTED_LOCALE}' > /etc/locale"
    echo "${SELECTED_LOCALE}" > /mnt/etc/locale
}


_install_yay() {
export USER_NAME
    cat << 'EOF' > /mnt/chroot/install_yay.sh
#!/bin/bash
_install_yay() {
    cd /tmp
    git clone https://aur.archlinux.org/yay.git
    chown -R $USER_NAME yay/
    cd yay/
    su -c "makepkg" $USER_NAME
    pacman -U --noconfirm yay-*.pkg.tar.zst
}
_install_yay
EOF
    chmod +x /mnt/chroot/install_yay.sh
    arch-chroot /mnt /chroot/install_yay.sh
    rm -rf /mnt/chroot/install_yay.sh
}

_install_paru() {
export USER_NAME
    cat << 'EOF' > /mnt/chroot/install_paru.sh
#!/bin/bash
install_paru() {
    cd /tmp
    git clone https://aur.archlinux.org/paru.git
    chown -R $USER_NAME paru/
    cd paru/
    su -c "makepkg" $USER_NAME
    pacman -U --noconfirm paru-*.pkg.tar.zst
}
install_paru
EOF
    chmod +x /mnt/chroot/install_paru.sh
    arch-chroot /mnt /chroot/install_paru.sh
    rm -rf /mnt/chroot/install_paru.sh
}

_run_symlink() {
    echo -e "Symlinking ${TEXT_EDITOR} Text Editor to vi"
    arch-chroot /mnt ln -sf /mnt/usr/bin/$TEXT_EDITOR /mnt/usr/bin/vi
}

clean_up() {
    rm -rf /mnt/chroot
}
